#!/usr/bin/env python3
"""Sign the exact AppSOFA feed bytes with an Ed25519 private key.

The private key is supplied only through APPSOFA_SIGNING_PRIVATE_KEY as the
base64-encoded 32-byte raw key generated by CryptoKit. The published signature
is base64 text and is verified by the macOS client before JSON decoding.
"""
import base64
import os
import pathlib
import sys

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

ROOT = pathlib.Path(__file__).resolve().parents[1]
FEED = ROOT / "public" / "v1" / "macos_apps_data_feed.json"
SIGNATURE = ROOT / "public" / "v1" / "macos_apps_data_feed.json.sig"

def main():
    encoded_key = os.environ.get("APPSOFA_SIGNING_PRIVATE_KEY", "").strip()
    if not encoded_key:
        raise RuntimeError("APPSOFA_SIGNING_PRIVATE_KEY is required")

    try:
        raw_key = base64.b64decode(encoded_key, validate=True)
    except Exception as exc:
        raise RuntimeError("APPSOFA_SIGNING_PRIVATE_KEY is not valid base64") from exc

    if len(raw_key) != 32:
        raise RuntimeError("APPSOFA_SIGNING_PRIVATE_KEY must decode to exactly 32 bytes")

    feed_data = FEED.read_bytes()
    private_key = Ed25519PrivateKey.from_private_bytes(raw_key)
    signature = private_key.sign(feed_data)

    SIGNATURE.write_text(
        base64.b64encode(signature).decode("ascii") + "\n",
        encoding="utf-8",
    )
    print("Signed:", FEED)
    print("Signature:", SIGNATURE)

if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"Signing failed: {exc}", file=sys.stderr)
        raise
